
const data = {
    products: [
        {
            _id: '1',
            name: 'Pinot Noir Rose',
            category: 'eighties',
            image: "/images/pinot-noir-rose-gold-1.jpg",
            certified: "/images/certified-green-2.jpg",
            price: 50,
            brand: 'Pinot Noir Rose',
            rating: 4.5,
            numReviews: 10,
            itemInStock: 5,
            description: 'high quality wine',
        },
        {
            _id: '2',
            name: 'Cabernet Basavin',
            category: 'seventies',
            image: '/images/cabernet.png',
            certified: "/images/certified-green-2.jpg",
            price: 20,
            brand: 'Cabernet Basavin',
            rating: 5,
            numReviews: 15,
            itemInStock: 9,
            description: 'high quality wine',
        },
        {
            _id: '3',
            name: 'Kagor Desert Wine',
            category: 'sixties',
            image: '/images/kagor.jpg',
            certified: "/images/certified-green-2.jpg",
            price: 28,
            brand: 'Kagor Desert Wine',
            rating: 4.9,
            numReviews: 19,
            itemInStock: 5,
            description: 'high quality wine',
        },
        {
            _id: '4',
            name: 'Chardonnay Gold',
            category: 'eighties',
            image: '/images/chardonnay-gold.jpg',
            certified: "/images/certified-green-2.jpg",
            price: 55,
            brand: 'Chardonnay Gold',
            rating: 4.5,
            numReviews: 7,
            itemInStock: 25,
            description: 'high quality wine',
        },
        {
            _id: '5',
            name: 'Pinot Grigio Rose',
            category: 'seventies',
            image: '/images/pinot-grigio-rose.png',
            certified: "/images/certified-green-2.jpg",
            price: 60,
            brand: 'Pinot-Grigio',
            rating: 4.7,
            numReviews: 15,
            itemInStock: 0,
            description: 'high quality wine',
        },
        {
            _id: '6',
            name: 'Chateau du Sauvignon',
            category: 'nineties',
            image: '/images/chateau-du-Basavines-Sauvignon.jpg',
            certified: "/images/certified-green-2.jpg",
            price: 70,
            brand: 'Chateau du Sauvignon',
            rating: 5,
            numReviews: 25,
            itemInStock: 12,
            description: 'high quality wine',
        },
    ],
};

export default data;